### ISSUE TITLE
write errors to stderr

### ISSUE THREAD

**Issue by niksu** [niksu/dosarray#2]
Currently error messages are sometimes written to stdout (e.g., https://github.com/niksu/dosarray/pull/1/commits/d87c55bfa7ae6c21f3e48366448b0a970a46ae4a#diff-4cf78e31b37364c390ea8c708e594d19R110) but this can make it more difficult to hunt down why the system failed.

**Comment by shilpiBose29** [comment]
Closed in 28f88c239018a4a9784e44cdeb91ab65331cf266
